title: Mes recettes
description: Recettes testées et approuvées
theme: minima

url: "https://phlered.github.io"
baseurl: "/recettes"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed

collections:
  recettes:
    output: true