title: Accueil
description: Recettes testées et approuvées
theme: minima
minima:
  skin: dark

url: "https://phlered.github.io"
baseurl: "/recettes"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed

include:
  - images

collections:
  recettes:
    output: true

header_pages:
  - about.md
  - search.md