title: Accueil
description: Recettes testées et approuvées


url: "https://phlered.github.io"
baseurl: "/recettes"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed

include:
  - images

collections:
  recettes:
    output: true
    permalink: /recettes/:name/

header_pages:
  - about.md
  - search.md